FROM golang:1.12 as builder
WORKDIR /go/src/github.com/opensciencegrid/gracc-collector
COPY . .
RUN CGO_ENABLED=0 go build -tags=netgo -ldflags="-X main.build_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)"

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /gracc
COPY --from=builder /go/src/github.com/opensciencegrid/gracc-collector/gracc-collector .
COPY --from=builder /go/src/github.com/opensciencegrid/gracc-collector/gracc.cfg .
CMD ["./gracc-collector"]
