version: '2'
services:
    elasticsearch:
        image: elasticsearch:5
        ports:
        - "9200:9200"
    rabbitmq:
        image: rabbitmq:management
        ports:
        - "15672:15672"
        - "5672:5672"
    zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
    kafka:
      image: wurstmeister/kafka
      ports:
          - "127.0.0.1:9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #volumes:
      #- /var/run/docker.sock:/var/run/docker.sock

    gracc-collector:
        image: opensciencegrid/gracc-collector
        environment:
        - GRACC_AMQP_HOST=rabbitmq
        - GRACC_AMQP_EXCHANGE=gracc.osg.raw
        - GRACC_LOGLEVEL=debug
        - GRACC_AMQP_DURABLE=true
        - GRACC_AMQP_AUTODELETE=false
        ports:
        - "8080:8080"
        depends_on:
        - rabbitmq
    gracc-stash-raw:
        image: opensciencegrid/gracc-stash-raw
        environment:
        - GRACC_INSTANCE=test
        - GRACC_STREAM=osg
        - ELASTICSEARCH_HOST=elasticsearch
        - AMQP_HOST=rabbitmq
        depends_on:
        - gracc-collector
        - elasticsearch
